services:
  backend:
    image: rajatrulaniya/hackdata-backend:latest
    ports:
      - "127.0.0.1:8000:8000"

  frontend:
    image: rajatrulaniya/hackdata-frontend:latest
    environment:
      BACKEND_HOST: hackdata.rajatrulaniya.com
      BACKEND_PORT: 443
    ports:
      - "127.0.0.1:3000:80"
    
    depends_on:
      - backend
